repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format .
        language: system
        pass_filenames: false

      - id: ruff-lint
        name: ruff lint
        entry: uv run ruff check .
        language: system
        pass_filenames: false

      - id: pyright
        name: pyright
        entry: uv run pyright .
        language: system
        pass_filenames: false

      - id: djlint
        name: djlint
        entry: uv run djlint --check templates/
        language: system
        pass_filenames: false

      - id: bun-check
        name: Check the format of static files
        entry: bun run check
        language: system
        pass_filenames: false
